microservices-umbrella-chart:
  deployment:
    initContainer:
      name: data-seed
      image: ahmedgrati/data-seed-job
      digest: sha256:85b6fd8502bc3a4bd2f47868f25ac00a5835d42a751166cec40fadb37951bc6c
      env:
        - name: MICROSERVICE
          value: videos
        - name: REDIS_HOST
          value: redis-master.databases
        - name: REDIS_PORT
          value: "6379"
    container:
      cpuLimit: 1
      cpuRequest: 0.5
      digest: sha256:5223789fdab6a145a41d3997c598ceed39036215257a2e24b8a57f8872422319
      env:
        - name: ENVIRONMENT
          value: DEBUG
        - name: REDIS_HOST
          value: redis-master.databases
        - name: REDIS_PORT
          value: "6379"
        - name: FLAKY
          value: "false"
      healthPath: /
      image: ahmedgrati/videos-ms
      memoryLimit: 500Mi
      memoryRequest: 500Mi
      name: videos-api-container
      port: 10010
    name: videos-api
    namespace: microservices
    replicas: 1
  serviceAccount:
    name: videos-api-sa
  service:
    name: videos-api
    type: ClusterIP
    ports:
      - protocol: TCP
        name: http
        port: 10010
        targetPort: 10010
