global:
  namespace: microservices
  databasePasswordSecret: videos-redis-secret
microservices-umbrella-chart:
  deployment:
    initContainer:
      name: data-seed
      image: ahmedgrati/data-seed-job
      digest: sha256:5ffd38163485b189e8824c01a61f174a118c9c9555c618728f2be85e2a32b025
    container:
      cpuLimit: 1
      cpuRequest: 0.5
      digest: sha256:538c424b87323b8c5aaac640f806ab6ede61fc5d84d517fb1bbb26caeca0681d
      image: ahmedgrati/videos-ms
      probe:
        readinessProbe:
          port: 10010
          path: /
        livenessProbe:
          port: 10010
          path: /
      memoryLimit: 500Mi
      memoryRequest: 500Mi
      name: videos-api-container
      ports:
        - name: application
          port: 10010
        - name: metrics
          port: 8000
    name: videos-api
    namespace: microservices
    replicas: 1
  serviceAccount:
    name: videos-api-sa
  service:
    name: videos-api
    type: ClusterIP
    ports:
      - protocol: TCP
        name: http
        port: 10010
        targetPort: 10010
      - protocol: TCP
        name: metrics
        port: 8000
        targetPort: 8000
  configmap:
    name: videos-env
    data:
      ENVIRONMENT: DEBUG
      REDIS_HOST: redis-master.databases
      REDIS_PORT: 6379
      FLAKY: false
      JAEGER_ENDPOINT: http://jaeger-collector.monitoring:14268/api/traces

  initConfigMap:
    name: videos-data-seed-env
    data:
      MICROSERVICE: videos
      REDIS_HOST: redis-master.databases
      REDIS_PORT: 6379
  monitoring:
    enabled: true
    interval: 20s
    targetPort: metrics
    path: /
